apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "infra-agent.fullname" . }}
  labels:
    {{- include "infra-agent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "infra-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "infra-agent.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "infra-agent.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: infra-agent
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: cache
              mountPath: /cache
            - name: varlogs
              mountPath: /var/logs
            - name: tmp
              mountPath: /tmp
          ports:
            - name: http
              containerPort: 9705
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            tcpSocket:
              port: http
          env:
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "infra-agent.fullname" . }}-config
                  key: HOST
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "infra-agent.fullname" . }}-config
                  key: PORT
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "infra-agent.fullname" . }}-config
                  key: LOG_LEVEL
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  name: {{ include "infra-agent.fullname" . }}-config
                  key: DEBUG
            - name: LOG_FORMAT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "infra-agent.fullname" . }}-config
                  key: LOG_FORMAT
            - name: GITLAB_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "infra-agent.fullname" . }}-config
                  key: GITLAB_URL
            - name: GITLAB_HELMFILE_PROJECT_PATH
              valueFrom:
                configMapKeyRef:
                  name: {{ include "infra-agent.fullname" . }}-config
                  key: GITLAB_HELMFILE_PROJECT_PATH
            - name: GITLAB_WEBHOOK_PROMPT_FORMAT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "infra-agent.fullname" . }}-config
                  key: GITLAB_WEBHOOK_PROMPT_FORMAT
            - name: GITLAB_WEBHOOK_SYSTEM_PROMPT_FORMAT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "infra-agent.fullname" . }}-config
                  key: GITLAB_WEBHOOK_SYSTEM_PROMPT_FORMAT
            - name: GITLAB_WEBHOOK_FOLLOWUP_PROMPT_FORMAT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "infra-agent.fullname" . }}-config
                  key: GITLAB_WEBHOOK_FOLLOWUP_PROMPT_FORMAT
            - name: GRAFANA_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "infra-agent.fullname" . }}-config
                  key: GRAFANA_URL
            - name: GRAFANA_ORG_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ include "infra-agent.fullname" . }}-config
                  key: GRAFANA_ORG_ID
            - name: GRAFANA_PROMETHEUS_DATASOURCE_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "infra-agent.fullname" . }}-config
                  key: GRAFANA_PROMETHEUS_DATASOURCE_NAME
            - name: GRAFANA_WEBHOOK_SYSTEM_PROMPT_FORMAT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "infra-agent.fullname" . }}-config
                  key: GRAFANA_WEBHOOK_SYSTEM_PROMPT_FORMAT
            - name: GRAFANA_WEBHOOK_PROMPT_FORMAT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "infra-agent.fullname" . }}-config
                  key: GRAFANA_WEBHOOK_PROMPT_FORMAT
            - name: GRAFANA_WEBHOOK_FOLLOWUP_PROMPT_FORMAT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "infra-agent.fullname" . }}-config
                  key: GRAFANA_WEBHOOK_FOLLOWUP_PROMPT_FORMAT
            - name: OPENAI_MODEL
              valueFrom:
                secretKeyRef:
                  name: {{ include "infra-agent.fullname" . }}-secrets
                  key: OPENAI_MODEL
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "infra-agent.fullname" . }}-secrets
                  key: OPENAI_API_KEY
            - name: GRAFANA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "infra-agent.fullname" . }}-secrets
                  key: GRAFANA_API_KEY
            - name: GITLAB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "infra-agent.fullname" . }}-secrets
                  key: GITLAB_TOKEN
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: cache
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        - name: temp
          emptyDir: {}
        - name: varlogs
          emptyDir: {}
